//! Conformance against the REAL official ECPayAIO_Python SDK: every vector
//! in `fixtures/python_sdk_vectors.json` was generated by executing the
//! upstream `sdk/ecpay_payment_sdk.py` (see `tests/fixtures/README.md`).
//!
//! Three deliberate divergences are pinned as such, not hidden:
//! * CheckMacValue escapes `~` to `%7e` (ECPay's .NET backend); the Python
//!   SDK hashes a literal `~`. See `tilde_divergence`.
//! * Invoice free-text fields are urlencoded but not lowercased (the SDK's
//!   `.lower()` corrupts ASCII letter case in customer data).
//! * Fields set outside their ChoosePayment group, and conflicting Credit
//!   plan groups, are validation errors (the SDK silently signs the mix).

use std::collections::{BTreeMap, HashMap};

use ecpay::payment::{
    union_pay, AioCheckOutParams, CarruerType, ChoosePayment, CreditAction, Donation, InvType,
    InvoiceExtend, PeriodType, PrintMark, TaxType,
};
use ecpay::Ecpay;

const FIXTURE: &str = include_str!("fixtures/python_sdk_vectors.json");

const TEST_MERCHANT_ID: &str = "3002607";
const TEST_HASH_KEY: &str = "pwFHCqoQZGmho4w6";
const TEST_HASH_IV: &str = "EkRm7iFT261dpevs";

fn sdk() -> Ecpay {
    Ecpay {
        merchant_id: TEST_MERCHANT_ID.to_owned(),
        hash_key: TEST_HASH_KEY.to_owned(),
        hash_iv: TEST_HASH_IV.to_owned(),
        ..Default::default()
    }
}

#[derive(serde::Deserialize)]
struct Fixture {
    create_order: HashMap<String, CreateOrderCase>,
    #[serde(default)]
    errors: HashMap<String, ErrCase>,
    check_value: HashMap<String, CheckValueCase>,
    html_form: HtmlFormCase,
    /// 156 seeded-random parameter maps signed by the real SDK (150
    /// tilde-free that must match byte-for-byte, 6 tilde-bearing that pin
    /// the %7e divergence).
    #[serde(default)]
    differential: HashMap<String, CheckValueCase>,
}

#[derive(serde::Deserialize)]
struct CreateOrderCase {
    #[serde(default)]
    ok: Option<Vec<Vec<String>>>,
}

#[derive(serde::Deserialize)]
struct ErrCase {
    error: Option<String>,
}

#[derive(serde::Deserialize)]
struct CheckValueCase {
    params: BTreeMap<String, String>,
    expected: String,
    #[serde(default)]
    dot_net_escaped: Option<String>,
}

#[derive(serde::Deserialize)]
struct HtmlFormCase {
    action: String,
    html: String,
}

fn fixture() -> Fixture {
    serde_json::from_str(FIXTURE).expect("parse python_sdk_vectors.json")
}

/// The scenario parameter sets, mirroring the generator's inputs (and the
/// official sample_*.py files) field for field. Empty-string optionals are
/// `None` — they drop out on the wire exactly like the SDK's filter stage.
fn scenario(name: &str) -> AioCheckOutParams {
    let mut p = match name {
        "credit_basic" => AioCheckOutParams {
            binding_card: Some(0),
            merchant_member_id: None,
            redeem: Some("N".into()),
            union_pay: Some(0),
            ..base(ChoosePayment::Credit)
        },
        "credit_installment" => AioCheckOutParams {
            credit_installment: Some("3,6,12".into()),
            ..base(ChoosePayment::Credit)
        },
        "credit_language" => AioCheckOutParams {
            language: Some("eng".into()),
            ..base(ChoosePayment::Credit)
        },
        "credit_period" => AioCheckOutParams {
            period_amount: Some(1000),
            period_type: Some(PeriodType::Month),
            frequency: Some(1),
            exec_times: Some(12),
            period_return_url: Some("https://www.ecpay.com.tw/period_return_url.php".into()),
            ..base(ChoosePayment::Credit)
        },
        "atm" => AioCheckOutParams {
            expire_date: Some(7),
            payment_info_url: Some("https://www.ecpay.com.tw/payment_info_url.php".into()),
            ..base(ChoosePayment::Atm)
        },
        "cvs" => AioCheckOutParams {
            store_expire_date: Some(10080),
            desc_1: Some("超商繳款說明1".into()),
            client_redirect_url: Some("https://www.ecpay.com.tw/client_redirect_url.php".into()),
            payment_info_url: Some("https://www.ecpay.com.tw/payment_info_url.php".into()),
            ..base(ChoosePayment::Cvs)
        },
        "barcode" => AioCheckOutParams {
            store_expire_date: Some(120),
            ..base(ChoosePayment::Barcode)
        },
        "all" => AioCheckOutParams {
            ignore_payment: Some("WebATM#BARCODE".into()),
            ..base(ChoosePayment::All)
        },
        "webatm" => AioCheckOutParams {
            choose_sub_payment: Some(ecpay::payment::choose_sub_payment::web_atm::TAISHIN.into()),
            ..base(ChoosePayment::WebATM)
        },
        "bnpl" => AioCheckOutParams {
            choose_sub_payment: Some(ecpay::payment::choose_sub_payment::bnpl::URICH.into()),
            ..base(ChoosePayment::Bnpl)
        },
        "digital" => AioCheckOutParams {
            choose_sub_payment: Some(
                ecpay::payment::choose_sub_payment::digital_payment::JKOPAY.into(),
            ),
            ..base(ChoosePayment::DigitalPayment)
        },
        "twqr" => base(ChoosePayment::Twqr),
        "weixin" => base(ChoosePayment::WeiXin),
        "googlepay" => base(ChoosePayment::GooglePay),
        "applepay" => base(ChoosePayment::ApplePay),
        "all_invoice" => AioCheckOutParams {
            ignore_payment: Some("WebATM#BARCODE".into()),
            invoice: Some(InvoiceExtend {
                relate_number: "Tea0001".into(),
                customer_name: Some("客戶名稱".into()),
                customer_addr: Some("台北市中正區100號".into()),
                customer_phone: Some("0912345678".into()),
                tax_type: TaxType::Dutiable,
                donation: Donation::No,
                print: PrintMark::No,
                invoice_item_name: "測試商品1#測試商品2".into(),
                invoice_item_count: "2#3".into(),
                invoice_item_word: "個#包".into(),
                invoice_item_price: "350#100".into(),
                invoice_remark: Some("測試商品說明".into()),
                delay_day: 0,
                inv_type: InvType::General,
                ..Default::default()
            }),
            invoice_mark: Some("Y".into()),
            ..base(ChoosePayment::All)
        },
        "credit_invoice_b2b" => AioCheckOutParams {
            invoice: Some(InvoiceExtend {
                relate_number: "Tea0002".into(),
                customer_id: Some("TEA_0000001".into()),
                customer_identifier: Some("53348111".into()),
                customer_name: Some("客戶名稱".into()),
                customer_addr: Some("台北市中正區100號".into()),
                customer_email: Some("abc@ecpay.com.tw".into()),
                tax_type: TaxType::Dutiable,
                donation: Donation::No,
                print: PrintMark::Yes,
                invoice_item_name: "測試商品1".into(),
                invoice_item_count: "2".into(),
                invoice_item_word: "個".into(),
                invoice_item_price: "350".into(),
                delay_day: 0,
                inv_type: InvType::General,
                ..Default::default()
            }),
            invoice_mark: Some("Y".into()),
            ..base(ChoosePayment::Credit)
        },
        "atm_expire_zero" => AioCheckOutParams {
            expire_date: Some(0),
            ..base(ChoosePayment::Atm)
        },
        other => panic!("unmapped create_order scenario {other:?}"),
    };
    // The invoice scenarios above carry their own mark (Y); the plain
    // scenarios in the generator send InvoiceMark='N' explicitly.
    if p.invoice.is_none() {
        p.invoice_mark.get_or_insert_with(|| "N".to_owned());
    }
    p
}

fn base(choose_payment: ChoosePayment) -> AioCheckOutParams {
    AioCheckOutParams {
        merchant_trade_no: "NO20240101120000".into(),
        merchant_trade_date: "2024/01/01 12:00:00".into(),
        total_amount: 2000,
        trade_desc: "訂單測試".into(),
        item_name: "商品1#商品2".into(),
        return_url: "https://www.ecpay.com.tw/return_url.php".into(),
        choose_payment,
        client_back_url: Some("https://www.ecpay.com.tw/client_back_url.php".into()),
        item_url: Some("https://www.ecpay.com.tw/item_url.php".into()),
        remark: Some("交易備註".into()),
        order_result_url: Some("https://www.ecpay.com.tw/order_result_url.php".into()),
        need_extra_paid_info: Some("Y".into()),
        ..Default::default()
    }
}

#[test]
fn create_order_matches_the_official_sdk() {
    let f = fixture();
    let client = sdk();
    let mut checked = 0;
    for (name, case) in &f.create_order {
        let Some(want) = &case.ok else {
            continue; // error scenarios covered by validation_messages_match
        };
        let got = client
            .aio_check_out(&scenario(name))
            .unwrap_or_else(|e| panic!("{name}: expected success, got {e}"));
        let want: Vec<(String, String)> = want
            .iter()
            .map(|kv| (kv[0].clone(), kv[1].clone()))
            .collect();
        // The two invoice scenarios diverge from the SDK on the wire in hex
        // case only (we do not lowercase the urlencoded free-text fields);
        // the decoded content and the CheckMacValue must still match.
        if name.contains("invoice") {
            assert_eq!(
                got.check_mac_value(),
                get_mac(&want),
                "{name}: CheckMacValue"
            );
            let decode = percent_decode;
            let got_decoded: Vec<(String, String)> = got
                .params()
                .iter()
                .map(|(k, v)| (decode(k), decode(v)))
                .collect();
            let want_decoded: Vec<(String, String)> =
                want.iter().map(|(k, v)| (decode(k), decode(v))).collect();
            assert_eq!(got_decoded, want_decoded, "{name}: decoded invoice params");
        } else {
            assert_eq!(
                got.into_pairs(),
                want,
                "{name}: final create_order params must match the official SDK byte-for-byte"
            );
        }
        checked += 1;
    }
    assert_eq!(checked, 18, "every ok scenario ran");
}

fn get_mac(pairs: &[(String, String)]) -> String {
    pairs
        .iter()
        .find(|(k, _)| k == "CheckMacValue")
        .map(|(_, v)| v.clone())
        .expect("CheckMacValue present")
}

/// Lenient percent-decode for comparing the two encoders' outputs.
fn percent_decode(s: &str) -> String {
    let b = s.as_bytes();
    let mut out = Vec::with_capacity(b.len());
    let mut i = 0;
    while i < b.len() {
        match b[i] {
            b'+' => {
                out.push(b' ');
                i += 1;
            }
            b'%' if i + 2 < b.len() => {
                let hex = |c: u8| (c as char).to_digit(16);
                if let (Some(hi), Some(lo)) = (hex(b[i + 1]), hex(b[i + 2])) {
                    out.push((hi * 16 + lo) as u8);
                    i += 3;
                } else {
                    out.push(b'%');
                    i += 1;
                }
            }
            c => {
                out.push(c);
                i += 1;
            }
        }
    }
    String::from_utf8_lossy(&out).into_owned()
}

#[test]
fn validation_messages_match_the_official_sdk() {
    let f = fixture();
    let client = sdk();
    let mut checked = 0;
    for (name, case) in &f.errors {
        let msg = case.error.clone().expect("the SDK raised");
        let err = client
            .aio_check_out(&error_scenario(name))
            .expect_err(&format!("{name}: expected a validation error"));
        assert_eq!(
            err.to_string(),
            format!("ecpay: {msg}"),
            "{name}: validation message must match the official SDK"
        );
        checked += 1;
    }
    // `errors` is `#[serde(default)]`: an empty or renamed fixture section
    // must not turn this into a vacuous pass.
    assert_eq!(checked, 11, "every error scenario in the fixture ran");
}

#[test]
fn check_values_match_the_official_sdk() {
    let f = fixture();
    let client = sdk();
    let map = |params: &BTreeMap<String, String>| {
        params.iter().map(|(k, v)| (k.clone(), v.clone())).collect()
    };

    // Same digest as the SDK for tilde-free params (SHA-256 and MD5).
    for (name, case) in &f.check_value {
        if name == "tilde_divergence" {
            continue;
        }
        let got = client.generate_check_value(&map(&case.params)).unwrap();
        assert_eq!(
            got, case.expected,
            "{name}: CheckMacValue must match the SDK"
        );
    }

    // The documented tilde divergence: the SDK hashes a literal ~, ECPay's
    // .NET backend (and this crate) escape it to %7e. `expected` pins the
    // SDK's literal-~ digest; `dot_net_escaped` pins what ECPay hashes.
    let tilde = &f.check_value["tilde_divergence"];
    let ours = check_mac_value_reference(&tilde.params);
    assert_eq!(
        ours,
        tilde.dot_net_escaped.as_deref().unwrap(),
        "this crate produces the .NET-escaped digest the ECPay server hashes"
    );
    assert_ne!(
        ours, tilde.expected,
        "and it diverges from the SDK's literal-~ digest by design"
    );
}

/// The .NET-HttpUtility contract recomputed with `check_mac_value`, proving
/// the escaped digest comes from the documented encoding change.
fn check_mac_value_reference(params: &BTreeMap<String, String>) -> String {
    let map: HashMap<String, String> = params.iter().map(|(k, v)| (k.clone(), v.clone())).collect();
    ecpay::check_mac_value(
        &map,
        TEST_HASH_KEY,
        TEST_HASH_IV,
        ecpay::EncryptType::Sha256,
    )
}

#[test]
fn html_form_matches_the_official_sdk() {
    let f = fixture();
    let client = Ecpay {
        payment_api_url: "https://payment-stage.ecpay.com.tw/Cashier/".into(),
        ..sdk()
    };
    let got = client
        .aio_check_out(&scenario("atm"))
        .expect("checkout builds");
    assert_eq!(got.action(), f.html_form.action);

    // The official SDK does not HTML-escape attribute values; ours does. The
    // vector's values contain no escapable characters, so the forms must be
    // identical modulo input ordering (ours is key-sorted).
    let inputs = |html: &str| -> Vec<String> {
        let mut v: Vec<String> = html
            .split("<input")
            .skip(1)
            .map(|s| {
                format!(
                    "<input{}",
                    &s[..s.find("/>").map(|i| i + 2).unwrap_or(s.len())]
                )
            })
            .collect();
        v.sort();
        v
    };
    assert_eq!(inputs(&got.html_form()), inputs(&f.html_form.html));
    let head = "<form id=\"data_set\" action=\"https://payment-stage.ecpay.com.tw/Cashier/AioCheckOut/V5\" method=\"post\">";
    let script = "<script type=\"text/javascript\">document.getElementById(\"data_set\").submit();</script></form>";
    assert!(got.html_form().starts_with(head));
    assert!(got.html_form().ends_with(script));
}

/// Large-scale differential test: every seeded-random parameter map must
/// produce the SAME digest as the real Python SDK, and the tilde-bearing
/// cases must produce the .NET-escaped digest instead (the documented
/// divergence).
#[test]
fn differential_corpus_matches_the_official_sdk() {
    let f = fixture();
    let client = sdk();
    assert!(
        f.differential.len() >= 150,
        "the vendored corpus should carry 150+ cases, got {}",
        f.differential.len()
    );
    let map = |params: &BTreeMap<String, String>| {
        params.iter().map(|(k, v)| (k.clone(), v.clone())).collect()
    };
    let mut plain = 0;
    let mut tilde = 0;
    for (name, case) in &f.differential {
        let got = client.generate_check_value(&map(&case.params)).unwrap();
        if name.starts_with("tilde") {
            tilde += 1;
            assert_ne!(
                got, case.expected,
                "{name}: tilde case unexpectedly matched the SDK"
            );
            assert_eq!(
                got,
                case.dot_net_escaped.as_deref().unwrap(),
                "{name}: tilde case must match the .NET-escaped contract"
            );
        } else {
            plain += 1;
            assert_eq!(
                got, case.expected,
                "{name}: digest diverges from the real SDK"
            );
        }
    }
    assert_eq!(plain, 150);
    assert_eq!(tilde, 6);
}

// --- The typed API's loud rejections (new behavior, documented) ---

#[test]
fn group_and_plan_conflicts_are_rejected() {
    let client = sdk();

    // ATM-only field with Credit.
    let err = client
        .aio_check_out(&AioCheckOutParams {
            expire_date: Some(7),
            ..base(ChoosePayment::Credit)
        })
        .expect_err("ExpireDate with Credit must be rejected");
    assert!(matches!(err, ecpay::Error::Validation(_)), "{err}");

    // PaymentInfoURL is shared by ATM and CVS/BARCODE: valid for CVS.
    client
        .aio_check_out(&AioCheckOutParams {
            payment_info_url: Some("https://x.example/paid".into()),
            ..base(ChoosePayment::Cvs)
        })
        .expect("PaymentInfoURL with CVS is valid");

    // Two Credit plan groups at once (the SDK silently signs the mix).
    let err = client
        .aio_check_out(&AioCheckOutParams {
            redeem: Some("N".into()),
            union_pay: Some(union_pay::ONLY),
            credit_installment: Some("3".into()),
            ..base(ChoosePayment::Credit)
        })
        .expect_err("mixed Credit plan groups must be rejected");
    assert!(matches!(err, ecpay::Error::Validation(_)), "{err}");

    // InvoiceMark=N with an invoice struct.
    let err = client
        .aio_check_out(&AioCheckOutParams {
            invoice_mark: Some("N".into()),
            invoice: Some(InvoiceExtend::default()),
            ..base(ChoosePayment::Credit)
        })
        .expect_err("InvoiceMark=N with invoice fields must be rejected");
    assert!(matches!(err, ecpay::Error::Validation(_)), "{err}");

    // extra: a colliding key is rejected, a fresh key is signed and sent.
    let err = client
        .aio_check_out(&AioCheckOutParams {
            extra: BTreeMap::from([("TotalAmount".into(), "1".into())]),
            ..base(ChoosePayment::Credit)
        })
        .expect_err("colliding extra key must be rejected");
    assert!(err.to_string().contains("collides"));
    let ok = client
        .aio_check_out(&AioCheckOutParams {
            extra: BTreeMap::from([("SomeFutureParam".into(), "42".into())]),
            ..base(ChoosePayment::Credit)
        })
        .expect("fresh extra key passes");
    assert!(
        ok.params()
            .iter()
            .any(|(k, v)| k == "SomeFutureParam" && v == "42"),
        "extra params ride along and get signed (their own CheckMacValue too)"
    );
}

#[test]
fn wire_constants_match_the_official_dicts() {
    assert_eq!(ChoosePayment::All.as_str(), "ALL");
    assert_eq!(ChoosePayment::Atm.as_str(), "ATM");
    assert_eq!(ChoosePayment::Barcode.as_str(), "BARCODE");
    assert_eq!(ChoosePayment::Bnpl.as_str(), "BNPL");
    assert_eq!(ChoosePayment::Twqr.as_str(), "TWQR");
    assert_eq!(ChoosePayment::Cvs.as_str(), "CVS");
    assert_eq!(ChoosePayment::Credit.as_str(), "Credit");
    assert_eq!(CreditAction::Close.as_str(), "C");
    assert_eq!(CreditAction::Refund.as_str(), "R");
    assert_eq!(CreditAction::Cancel.as_str(), "E");
    assert_eq!(CreditAction::Abandon.as_str(), "N");
    assert_eq!(union_pay::ONLY, 1);
    assert_eq!(union_pay::SELECT, 0);
    assert_eq!(union_pay::HIDDEN, 2);
}

fn error_scenario(name: &str) -> AioCheckOutParams {
    let invoice = |print: PrintMark, donation: Donation| InvoiceExtend {
        relate_number: "T1".into(),
        customer_name: Some("客戶".into()),
        customer_addr: Some("地址".into()),
        customer_phone: Some("0912345678".into()),
        tax_type: TaxType::Dutiable,
        donation,
        print,
        invoice_item_name: "商品".into(),
        invoice_item_count: "1".into(),
        invoice_item_word: "個".into(),
        invoice_item_price: "10".into(),
        delay_day: 0,
        inv_type: InvType::General,
        ..Default::default()
    };
    match name {
        "missing_item_name" => AioCheckOutParams {
            item_name: String::new(),
            ..base(ChoosePayment::Credit)
        },
        "too_long_trade_no" => AioCheckOutParams {
            merchant_trade_no: "A".repeat(21),
            ..base(ChoosePayment::Credit)
        },
        "identifier_not_8" => AioCheckOutParams {
            invoice: Some(InvoiceExtend {
                customer_identifier: Some("123".into()),
                ..invoice(PrintMark::No, Donation::No)
            }),
            invoice_mark: Some("Y".into()),
            ..base(ChoosePayment::Credit)
        },
        "identifier_with_carrier" => AioCheckOutParams {
            invoice: Some(InvoiceExtend {
                customer_identifier: Some("53348111".into()),
                carruer_type: Some(CarruerType::Cellphone),
                ..invoice(PrintMark::Yes, Donation::No)
            }),
            invoice_mark: Some("Y".into()),
            ..base(ChoosePayment::Credit)
        },
        "print_without_name" => AioCheckOutParams {
            invoice: Some(InvoiceExtend {
                customer_name: None,
                ..invoice(PrintMark::Yes, Donation::No)
            }),
            invoice_mark: Some("Y".into()),
            ..base(ChoosePayment::Credit)
        },
        "no_email_no_phone" => AioCheckOutParams {
            invoice: Some(InvoiceExtend {
                customer_phone: None,
                ..invoice(PrintMark::No, Donation::No)
            }),
            invoice_mark: Some("Y".into()),
            ..base(ChoosePayment::Credit)
        },
        "donation_without_love_code" => AioCheckOutParams {
            invoice: Some(invoice(PrintMark::No, Donation::Yes)),
            invoice_mark: Some("Y".into()),
            ..base(ChoosePayment::Credit)
        },
        "love_code_too_short" => AioCheckOutParams {
            invoice: Some(InvoiceExtend {
                love_code: Some("1".into()),
                ..invoice(PrintMark::No, Donation::Yes)
            }),
            invoice_mark: Some("Y".into()),
            ..base(ChoosePayment::Credit)
        },
        "donation_with_print" => AioCheckOutParams {
            invoice: Some(InvoiceExtend {
                love_code: Some("168001".into()),
                ..invoice(PrintMark::Yes, Donation::Yes)
            }),
            invoice_mark: Some("Y".into()),
            ..base(ChoosePayment::Credit)
        },
        "tachong_rejected" => AioCheckOutParams {
            choose_sub_payment: Some(ecpay::payment::choose_sub_payment::web_atm::TACHONG.into()),
            ..base(ChoosePayment::WebATM)
        },
        "sinopac_rejected" => AioCheckOutParams {
            choose_sub_payment: Some(ecpay::payment::choose_sub_payment::web_atm::SINOPAC.into()),
            ..base(ChoosePayment::WebATM)
        },
        other => panic!("unmapped error scenario {other:?}"),
    }
}
